services:
  redis:
    image: redis:alpine
    container_name: frodo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: frodo-selenium
    ports:
      - "14440:4444"
    environment:
      - SE_NODE_ENABLE_MANAGED_DOWNLOADS=true
      - SE_OPTS=--enable-managed-downloads true
      - SE_LOG_LEVEL=INFO
    #      - SE_BROWSER_ARGS_INCOGNITO=--incognitos
    restart: always
    shm_size: 4gb

  backend:
    build:
      context: ./backend
    container_name: frodo-backend
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 7013
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /app
    ports:
      - "18000:7013"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=frodo-redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend
    container_name: frodo-frontend
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./frontend/app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/app/package.json
          target: /app/package.json
    ports:
      - "13000:3000"
    depends_on:
      - n8n

  n8n:
    image: n8nio/n8n
    container_name: frodo-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis

volumes:
  redis_data:
  n8n_data:
